name: Blueprints Notification

on:
  push:
    branches: [main]
    paths:
      - "blueprints/Data/bp-contracts_short.json"

  workflow_dispatch:

jobs:
  deploy_blueprints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 30

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests
          sudo apt-get update && sudo apt-get install -y locales
          sudo sed -i '/de_DE.UTF-8/s/^# //g' /etc/locale.gen && sudo locale-gen

      - name: Execute blueprints notification
        env:
          LANG: de_DE.UTF-8
          LANGUAGE: de_DE:de
          LC_ALL: de_DE.UTF-8
          TZ: "Europe/Berlin"
          DISCORD_WEBHOOK_URL_BP: ${{ secrets.DISCORD_WEBHOOK_URL_BP }}
        run: python .github/workflows/deploy_script.py --blueprints
