name: global.ini Tests
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  test:
    name: ${{ matrix.test.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test:
          - name: "Check For Missing Keys"
            script: "key_test.py"
            custom-args: ""
          - name: "Ensure Matching Encodings"
            script: "encoding_test.py"
            deps: "chardet"
            custom-args: ""
          - name: "Check For Whitespaces Before Comma"
            script: "whitespace_comma_test.py"
            custom-args: ""
          - name: "Check For Double Whitespaces"
            script: "double_whitspace_test.py"
            custom-args: ""
          - name: "Check For Not Closed Brackets"
            script: "bracket_test.py"
            custom-args: ""
          - name: "Check For wrong and missing descriptions"
            script: "item_desc_test.py"
            custom-args: ""
          - name: "Check For n Without Backslash"
            script: "n_without_backslash_test.py"
            custom-args: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Dependencies
        if: matrix.test.deps
        run: |
          python -m pip install --upgrade pip
          pip install ${{ matrix.test.deps }}

      - name: Execute Test
        run: python ./.github/tests/${{ matrix.test.script }} --github ${{ (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') && '--fail-on-error' || '' }} ${{ matrix.test.custom-args }}
